# Generated by Django 5.0.2 on 2024-10-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='follower',
        ),
        migrations.AddField(
            model_name='follower',
            name='follower_identifier',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
